### ISSUE TITLE
Specify dependencies

### ISSUE THREAD

**Issue by schmitts** [fmi-basel/gzenke-nonlinear-transient-amplification#1]
Please specify which versions of the third party libraries, e.g. numpy, have been used for the publication and which minimal/maximal versions you expect to use. Please also specify the version of Python.

**Comment by yuekriswu** [comment]
Python 3.7; h5py 2.10.0; matplotlib 3.2.1; numpy 1.18.4; matplotlib 3.2.1; scipy 1.6; seaborn 0.10.1. FYI.
